HOST = "0.0.0.0"
PORT = 8765

MAX_JUMP_COUNT = 2
MOVEMENT_MULTIPLIER = 0.2

# 简化地图参数
GROUND_EPSILON = 0.001
PLAYER_HALF_WIDTH = 0.46
PLAYER_HALF_HEIGHT = 0.42

# 统一运动参数，建议和 Unity Fixed Timestep / 玩家 moveSpeed 保持一致。
SIM_DT = 0.05
MOVE_SPEED = 16.0 * MOVEMENT_MULTIPLIER

GRAVITY = -2.0 * MOVEMENT_MULTIPLIER
JUMP_VELOCITY = 30.0 * MOVEMENT_MULTIPLIER
FALL_SPEED_CAP = -36.0 * MOVEMENT_MULTIPLIER
OFFSET_Y = 0.7
GROUND_Y = -1.45 + OFFSET_Y
